export const dateRanges = [
    {
        id: 1,
        start: 1982,
        end: 2001,
        nameEvents: 'Компьютеры',
        events: [
            { id: 1, year: 1982, text: 'Выпущен Commodore 64 — самый продаваемый компьютер в истории.' },
            { id: 3, year: 1984, text: 'Apple выпускает Macintosh с графическим интерфейсом.' },
            { id: 4, year: 1985, text: 'Microsoft выпускает Windows 1.0.' },
            { id: 11, year: 1992, text: 'Microsoft представляет Windows 3.1.' },
            { id: 14, year: 1995, text: 'Windows 95 запускает новую эру с Internet Explorer.' },
            { id: 20, year: 2001, text: 'Apple запускает Mac OS X.' },
        ],
    },
    {
        id: 2,
        start: 1988,
        end: 2011,
        nameEvents: 'Интернет',
        events: [
            { id: 7, year: 1988, text: 'Запуск IRC для онлайн-общения.' },
            { id: 8, year: 1989, text: 'Тим Бернерс-Ли создает World Wide Web.' },
            { id: 12, year: 1993, text: 'Запущен первый веб-браузер Mosaic.' },
            { id: 13, year: 1994, text: 'Основана Netscape Communications.' },
            { id: 17, year: 1998, text: 'Ларри Пейдж и Сергей Брин основали Google.' },
            { id: 30, year: 2011, text: 'Запуск социальной сети Google+.' },
        ],
    },
    {
        id: 3,
        start: 1987,
        end: 2009,
        nameEvents: 'Программирование',
        events: [
            { id: 2, year: 1983, text: 'Создан язык программирования C++.' },
            { id: 6, year: 1987, text: 'Выпущен первый символьный пакет Mathematica.' },
            { id: 15, year: 1996, text: 'Sun Microsystems создает язык Java.' },
            { id: 10, year: 1991, text: 'Линус Торвальдс запускает проект Linux.' },
            { id: 28, year: 2009, text: 'Создание криптовалюты Bitcoin.' },
        ],
    },
    {
        id: 4,
        start: 1985,
        end: 2006,
        nameEvents: 'Мультимедиа',
        events: [
            { id: 5, year: 1986, text: 'Основана студия Pixar.' },
            { id: 9, year: 1990, text: 'Adobe запускает Photoshop 1.0.' },
            { id: 24, year: 2005, text: 'Запущен YouTube.' },
            { id: 25, year: 2006, text: 'Twitter запускает свою платформу микроблогов.' },
        ],
    },
    {
        id: 5,
        start: 1997,
        end: 2007,
        nameEvents: 'Технологические прорывы',
        events: [
            { id: 16, year: 1997, text: 'IBM Deep Blue обыгрывает Гарри Каспарова в шахматы.' },
            { id: 18, year: 1999, text: 'Запущен Napster, первая популярная P2P сеть.' },
            { id: 19, year: 2000, text: 'Лопнул пузырь доткомов, вызвав кризис в IT.' },
            { id: 26, year: 2007, text: 'Apple выпускает первый iPhone.' },
        ],
    },
    {
        id: 6,
        start: 2002,
        end: 2010,
        nameEvents: 'Онлайн-коммуникации',
        events: [
            { id: 21, year: 2002, text: 'Microsoft запускает .NET Framework.' },
            { id: 22, year: 2003, text: 'Выпущен Skype для звонков через интернет.' },
            { id: 23, year: 2004, text: 'Марк Цукерберг создает Facebook.' },
            { id: 29, year: 2010, text: 'Запущен Instagram.' },
        ],
    },
];
